Proposition d'amélioration de l'installation de base
marsante/MedShakeEHR-Ansible pull request #1
Opened 2021-04-24 07:31 UTC by indelog

Je propose quelques améliorations sur l'installation de base : 

- Ajout d'une variable de configuration pour permettre la désactivation de la création du certifcat auto-signé pour l'accès web MSEHR (peut être utile si on choisis d'utiliser d'autres certificats, par exemple générer avec lets'encrypt).
- Ajout de variable de configuration pour permettre le choix du dépôt et de la version pour la récupération de l'archive MSEHR ainsi que du check de l'intégrité de l'archive récupéré.
- Crée l'utilisateur de la base de donnée et utilise le script d'installation cli pour finallisé l'installtion MSEHR (fournis directement l'installation "clé en main")

Je modifie aussi un peut la config de base ansible pour utiliser l'interpréteur python3 se qui permet d'utiliser le module ansible *openssl* sans avoir besoin d'inclure la lib avec *pip*.

PS : Je travail sur l'inclusion d'un role pour OpenVPN et d'un autres pour générer une PKI.

2021-05-30 22:18 UTC, marsante requested changes
Merci beaucoup ! top pour la modification de l'interprétateur python3.
J'ai tout testé jusqu'à composer. 
J'ai l'erreur suivante Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache Cannot create cache directory /var/www/.composer/cache/files/
Concernant la modification du fichier ansible.cfg c'est non fonctionnel sur box vagrant.
J'avais un autre bug sur composer, mais ça venait du fait que les acl ne sont pas installés sur les box debian 10.
Il y avait aussi une erreur à cause du nommage du paquet python3-mysqldb, c'est fixé.
Concernant l'ordre des rôles, les handlers se font normalement à la fin. Il faut au moins garder le rôle php au-dessus de celui de medshakeehr pour que les paquets de composer puissent utiliser les extensions php
J'ai oublié de partager la branche openvpn je le fais de suite. Il manque à choisir les variables d'intérêt du rôle galaxy, ça sera probablement plus simple à maintenir ainsi.
Y aurait-il moyen d'automatiser le sha ? Sinon il va falloir que je commit à chaque modification de version

2021-05-30 22:18 UTC, marsante commented on ansible.cfg
> -[privilege_escalation]
je n'arrive pas à provisionner une box vagrant avec ce code. J'ai des messages d'erreurs sur une absence d'accès aux fichiers et dossier privilégiés
pour reproduire, vagrant up à la première création ou vagrant provision

2021-05-31 07:57 UTC, indelog commented
Pour l'erreur avec composer je pense que cela provient du fait que composer est exécuté avec l'utilisateur `www-data` (avec `become_user: www-data`) et que par défaut `/var/www/` n'est inscriptible que par root. On peut soit désactiver le cache en passant à composer le paramètre `--no-cache` à composer ou soit déplacer sont emplacement de cache dans `/tmp/` en définissant la variable d’environement `COMPOSER_CACHE_DIR=/tmp/composer/` par exemple.

Pour Vargant désolé, vu que je ne l'utilise pas je n'en connaît pas les spécificités. Si j'ai bien compris il provisionne avec un utilisateur non privilégié ?

J'ai vu que tu as remplacé `python3-mysqldb` par `python-mysqldb`, normalement si on utilise pyton3 c'est `python3-mysqldb` qui est utilisé par l'interpréteur python ? Tu as eu des erreurs durant l'exécution du playbook ?

Pour openvpn il manque un role pour gérer les certificat TLS (le moyen le plus fiable pour authentifier les clients). J'ai pas trouvé de role qui fonctionnait comme je voulais, j'en ai donc fait un qui utilise EasyRSA : <https://framagit.org/indelog/ansible-role-easyrsa> . Il permet de assez finement les révocation et renouvellement et fournir un service qui notifie par courriel l'expiration des certificats.

J'ai commencé aussi à écrire un role OpenVPN plus simple (moins de variable de config) que celui de kyl191 orienté pour Debian et qui puisse gérer des configuration personnalisé pour les client (ce que j'ai besoin à titre personnel), par contre il est beaucoup moins complet en matière de possibilité de configuration d'OpenVPN. Mais j'ai pas encore publier car c'est pas fini (j’espère le terminer dans le mois qui viens).

Pour le sha, je voit pas comment faire autrement pour le moment que le mettre à jours à chaque fois, c'est le seul moyen qu'on a actuellement de contrôler l'intégrité du fichier récupérer. La solution alternative aurai été de signer le paquet avec GPG mais il ne l'est pas.

2021-06-01 20:31 UTC, marsante commented
composer est en version 1.8 sur debian 10, donc il ne dispose pas encore de la fonction --no-cache ni de la variable compose_cache_dir. Je vais rajouter un rôle composer pour installer la version 2.
ça peut être intéressant d'utiliser vagrant pour partir d'une debian 10 minimal et constater ce qui manque.

J'ai résolu le problème du become de vagrant via une variable dans le vagrantfile.

Le bug de python3-mysqldb ne survient plus depuis que j'ai détruit et réup une nouvelle debian 10. C'est même maintenant l'inverse python-mysqldb qui ne fonctionne plus. Je remodifierai ça.

Concernant la génération des clefs rsa il y a [ce role galaxy pour easyrsa](https://github.com/nkakouros-original/ansible-role-easyrsa) si besoin

2021-06-01 21:32 UTC, merged

2021-06-01 21:39 UTC, marsante commented
Merci pour les ajouts. Je reteste une dernière fois le playbook à partir de 0 sur la branch de test et si c'est bon je merge dans master